config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: :show
  namespace :admin do
    resources :properties
    resources :property_situations, except: [:show]
    resources :property_standard_items, except: [:show]
    resources :property_types, except: [:show]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboards#go_to_home"
end

app/views/layouts/admin/_footer.html.erb
<footer class="footer footer-transparent d-print-none">
  <div class="container-xl">
    <div class="row text-center align-items-center flex-row-reverse">
      <div class="col-lg-auto ms-lg-auto">
        <ul class="list-inline list-inline-dots mb-0">
          <li class="list-inline-item">
            <a
              href="https://tabler.io/docs"
              target="_blank"
              class="link-secondary"
              rel="noopener"
              >Documentation</a
            >
          </li>
          <li class="list-inline-item">
            <a href="./license.html" class="link-secondary">License</a>
          </li>
          <li class="list-inline-item">
            <a
              href="https://github.com/tabler/tabler"
              target="_blank"
              class="link-secondary"
              rel="noopener"
              >Source code</a
            >
          </li>
          <li class="list-inline-item">
            <a
              href="https://github.com/sponsors/codecalm"
              target="_blank"
              class="link-secondary"
              rel="noopener"
            >
              <!-- Download SVG icon from http://tabler-icons.io/i/heart -->
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="icon text-pink icon-filled icon-inline"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                stroke-width="2"
                stroke="currentColor"
                fill="none"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <path
                  d="M19.5 12.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572"
                />
              </svg>
              Sponsor
            </a>
          </li>
        </ul>
      </div>
      <div class="col-12 col-lg-auto mt-3 mt-lg-0">
        <ul class="list-inline list-inline-dots mb-0">
          <li class="list-inline-item">
            Copyright &copy; 2023
            <a href="." class="link-secondary">Tabler</a>. All rights
            reserved.
          </li>
          <li class="list-inline-item">
            <a
              href="./changelog.html"
              class="link-secondary"
              rel="noopener"
            >
              v1.0.0-beta20
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/admin/_header.html.erb
<header class="navbar navbar-expand-md d-print-none navbar-dark" data-bs-theme="dark">
  <div class="container-xl">
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbar-menu"
      aria-controls="navbar-menu"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <h1
      class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3"
    >
     <%= link_to root_path do %>
        <%= image_tag "logo-sistema.svg", height: 39, width: 91, alt: "Imóvel Simples", class: "navbar-brand-image" %>
     <% end %> 
    </h1>
    <div class="navbar-nav flex-row order-md-last">
      <div class="nav-item dropdown">
        <a
          href="#"
          class="nav-link d-flex lh-1 text-reset p-0"
          data-bs-toggle="dropdown"
          aria-label="Open user menu"
        >
          <span
            class="avatar avatar-sm"
            style="background-image: url(./static/avatars/000m.jpg)"
          ></span>
          <div class="d-none d-xl-block ps-2">
            <div><%= current_user.email %></div>
            <div class="mt-1 small text-secondary"><%= current_user.email %></div>
          </div>
        </a>
        <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
          <a href="#" class="dropdown-item">Perfil</a>
          <div class="dropdown-divider"></div>
          <%= link_to "Sair", destroy_user_session_path, class: "dropdown-item", data: { turbo_method: :delete } %>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/admin/_navbar.html.erb
<header class="navbar-expand-md">
  <div class="collapse navbar-collapse" id="navbar-menu">
    <div class="navbar">
      <div class="container-xl">
        <div class="row flex-fill align-items-center">
          <div class="col">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to root_path, class: "nav-link" do %>
                  <span class="nav-link-icon d-md-none d-lg-inline-block">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      class="icon"
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      stroke-width="2"
                      stroke="currentColor"
                      fill="none"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    >
                      <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                      <path d="M5 12l-2 0l9 -9l9 9l-2 0" />
                      <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7" />
                      <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6" />
                    </svg>
                  </span>
                  <span class="nav-link-title"> Página Inicial </span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to "Imóveis", admin_properties_path, class: 'nav-link' %>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#navbar-help" data-bs-toggle="dropdown" data-bs-auto-close="outside" role="button" aria-expanded="false" >
                  <i class="nav-link-icon fs-2 d-md-none d-lg-inline-block ti ti-list"></i>
                  <span class="nav-link-title">
                    Tabelas Auxiliares
                  </span>
                </a>
                <div class="dropdown-menu">
                  <%= link_to "Situação", admin_property_situations_path, class: "dropdown-item" %>
                  <%= link_to "Características", admin_property_standard_items_path, class: "dropdown-item" %>
                  <%= link_to "Tipos de Imóvel", admin_property_types_path, class: "dropdown-item" %>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>