config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: :show
  namespace :admin do
    resources :properties
    resources :property_situations, except: [:show]
    resources :property_standard_items, except: [:show]
    resources :property_types, except: [:show]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboards#go_to_home"
end

app/models/property_situation.rb
class PropertySituation < ApplicationRecord
end

app/controllers/admin/property_situations_controller.rb
module Admin
  class PropertySituationsController < BaseController
    before_action :load_property_type, only: [:edit, :update, :destroy]

    def index
      @property_situations = PropertySituation.order(:name)
    end

    def new
      @property_situation = PropertySituation.new
    end

    def create
      @property_situation = PropertySituation.new property_situation_params
      if @property_situation.save
        redirect_to admin_property_situations_path, notice: 'Tipo de Imóvel criado com sucesso!'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit;end

    def update
      if @property_situation.update property_situation_params
        redirect_to admin_property_situations_path, notice: 'Tipo de Imóvel atualizado com sucesso!'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @property_situation.destroy
      redirect_to admin_property_situations_path, notice: 'Tipo de Imóvel excluído com sucesso!'
    end

    private

    def load_property_situation
      @property_situation = PropertySituation.find params[:id]
    end

    def property_situation_params
      params.require(:property_situation).permit(:name)
    end
  end
end

app/helpers/admin/property_situations_helper.rb
module Admin::PropertySituationsHelper
end

app/views/admin/property_situations/_collection_table.html.erb
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Lista</h3>
    <div class="card-actions">
      <%= link_to new_admin_property_situation_path, class: "btn btn-primary" do %>
        <i class="ti ti-plus"></i>
        Adicionar Novo
      <% end %>
    </div>
  </div>
  <div class="table-responsive">
    <table class="table table-vcenter table-mobile-md card-table">
      <thead>
        <tr>
          <th><%= t "Name" %></th>
          <th class="w-1"></th>
        </tr>
      </thead>
      <tbody>
        <%= render @property_situations %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/property_situations/_form.html.erb
<%= simple_form_for [:admin, @property_situation] do |form| %>
  <%= render(CardComponent.new(title: resource_form_title)) do |component| %>
    <%= form.input :name, input_html: { class: 'form-control mt-2 mb-2' } %>

    <% component.with_footer do %>
      <%= form.button :button %>
    <% end %>
  <% end %>
<% end %>

app/views/admin/property_situations/_property_situation.html.erb
<tr>
  <td data-label="Name">
    <div class="d-flex py-1 align-items-center">
      <div class="flex-fill">
        <div class="font-weight-medium">
          <%= property_situation.name %>
        </div>
      </div>
    </div>
  </td>
  <td>
    <div class="btn-list flex-nowrap">
      <%= link_to edit_admin_property_situation_path(property_situation), class: "btn btn-icon" do %>
        <i class="ti ti-pencil"></i>
      <% end %>
      <%= button_to admin_property_situation_path(property_situation), method: :delete, class: "btn btn-danger btn-icon", data: { turbo_confirm: 'Você tem certeza?' } do %>
        <i class="ti ti-trash"></i>
      <% end %>
    </div>
  </td>
</tr>