config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: :show
  namespace :admin do
    resources :properties
    resources :property_situations, except: [:show]
    resources :property_standard_items, except: [:show]
    resources :property_types, except: [:show]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboards#go_to_home"
end

app/controllers/admin/property_types_controller.rb
module Admin
  class PropertyTypesController < BaseController
    before_action :load_property_type, only: [:edit, :update, :destroy]

    def index
      @property_types = PropertyType.order(:name)
    end

    def new
      @property_type = PropertyType.new
    end

    def create
      @property_type = PropertyType.new property_type_params
      if @property_type.save
        redirect_to admin_property_types_path, notice: 'Tipo de Imóvel criado com sucesso!'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit;end

    def update
      if @property_type.update property_type_params
        redirect_to admin_property_types_path, notice: 'Tipo de Imóvel atualizado com sucesso!'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @property_type.destroy
      redirect_to admin_property_types_path, notice: 'Tipo de Imóvel excluído com sucesso!'
    end

    private

    def load_property_type
      @property_type = PropertyType.find params[:id]
    end

    def property_type_params
      params.require(:property_type).permit(:name)
    end
  end
end

app/helpers/admin/property_types_helper.rb
module Admin::PropertyTypesHelper
end

app/views/admin/property_types/_collection_table.html.erb
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Lista</h3>
    <div class="card-actions">
      <%= link_to new_admin_property_type_path, class: "btn btn-primary" do %>
        <i class="ti ti-plus"></i>
        Adicionar Novo
      <% end %>
    </div>
  </div>
  <div class="table-responsive">
    <table class="table table-vcenter table-mobile-md card-table">
      <thead>
        <tr>
          <th><%= t "Name" %></th>
          <th class="w-1"></th>
        </tr>
      </thead>
      <tbody>
        <%= render @property_types %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/property_types/_form.html.erb
<%= simple_form_for [:admin, @property_type] do |form| %>
  <%= render(CardComponent.new(title: resource_form_title)) do |componente| %>
      <%= form.input :name %>

      <% componente.with_footer do %>
        <%= form.submit "Enviar", class: 'btn btn-success' %>
      <% end %>  
  <% end %>
<% end %>
  

app/views/admin/property_types/_property_type.html.erb
<tr>
  <td data-label="Name">
    <div class="d-flex py-1 align-items-center">
      <div class="flex-fill">
        <div class="font-weight-medium">
          <%= property_type.name %>
        </div>
      </div>
    </div>
  </td>
  <td>
    <div class="btn-list flex-nowrap">
      <%= link_to edit_admin_property_type_path(property_type), class: "btn btn-icon" do %>
        <i class="ti ti-pencil"></i>
      <% end %>
      <%= button_to admin_property_type_path(property_type), method: :delete, class: "btn btn-danger btn-icon", data: { turbo_confirm: 'Você tem certeza?' } do %>
        <i class="ti ti-trash"></i>
      <% end %>
    </div>
  </td>
</tr>