config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: :show
  namespace :admin do
    resources :properties
    resources :property_situations, except: [:show]
    resources :property_standard_items, except: [:show]
    resources :property_types, except: [:show]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboards#go_to_home"
end

app/models/property_standard_item.rb
class PropertyStandardItem < ApplicationRecord
  validates :name, presence: true
  validates :name, length: { maximum: 100 }
end

app/controllers/admin/property_standard_items_controller.rb
module Admin
  class PropertyStandardItemsController < BaseController
    before_action :load_property_standard_item, only: [:edit, :update, :destroy]

    def index
      @property_standard_items = PropertyStandardItem.order(:name)
    end

    def new
      @property_standard_item = PropertyStandardItem.new
    end

    def create
      @property_standard_item = PropertyStandardItem.new property_standard_item_params
      if @property_standard_item.save
        redirect_to admin_property_standard_items_path, notice: 'Característica criado com sucesso!'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit;end

    def update
      if @property_standard_item.update property_standard_item_params
        redirect_to admin_property_standard_items_path, notice: 'Característica atualizado com sucesso!'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @property_standard_item.destroy
      redirect_to admin_property_standard_items_path, notice: 'Característica excluído com sucesso!'
    end

    private

    def load_property_standard_item
      @property_standard_item = PropertyStandardItem.find params[:id]
    end

    def property_standard_item_params
      params.require(:property_standard_item).permit(:name)
    end
  end
end

app/helpers/admin/property_standard_items_helper.rb
module Admin::PropertyStandardItemsHelper
end

app/views/admin/property_standard_items/_collection_table.html.erb
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Lista</h3>
    <div class="card-actions">
      <%= link_to new_admin_property_standard_item_path, class: "btn btn-primary" do %>
        <i class="ti ti-plus"></i>
        Adicionar Novo
      <% end %>
    </div>
  </div>
  <div class="table-responsive">
    <table class="table table-vcenter table-mobile-md card-table">
      <thead>
        <tr>
          <th><%= t "Name" %></th>
          <th class="w-1"></th>
        </tr>
      </thead>
      <tbody>
        <%= render @property_standard_items %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/property_standard_items/_form.html.erb
<%= simple_form_for [:admin, @property_standard_item] do |form| %>
  <%= render(CardComponent.new(title: resource_form_title)) do |component| %>
    <%= form.input :name, input_html: { class: 'form-control mt-2 mb-2' } %>

    <% component.with_footer do %>
      <%= form.button :button %>
    <% end %>
  <% end %>
<% end %>

app/views/admin/property_standard_items/_property_standard_item.html.erb
<tr>
  <td data-label="Name">
    <div class="d-flex py-1 align-items-center">
      <div class="flex-fill">
        <div class="font-weight-medium">
          <%= property_standard_item.name %>
        </div>
      </div>
    </div>
  </td>
  <td>
    <div class="btn-list flex-nowrap">
      <%= link_to edit_admin_property_standard_item_path(property_standard_item), class: "btn btn-icon" do %>
        <i class="ti ti-pencil"></i>
      <% end %>
      <%= button_to admin_property_standard_item_path(property_standard_item), method: :delete, class: "btn btn-danger btn-icon", data: { turbo_confirm: 'Você tem certeza?' } do %>
        <i class="ti ti-trash"></i>
      <% end %>
    </div>
  </td>
</tr>